version: '3.6'

services:

  shop-bot:
    build:
      context: .
    working_dir:
      /shop_bot/
    env_file:
      - .env
    command:
      python -m pytest
#      python /shop_bot/src/manage.py
    volumes:
      - ./src:/shop_bot/src/
#    depends_on:
#     - redis
#
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"